function showPatchNotesV200(lc, rc)
    local bugFixes = {
        'Fixed not being able to properly store some cursor trail parameters.',
        'Fixed start/end expo using incorrect algorithm.',
        'Fixed all bugs relating to automate.',
        'Removed v1.1.2 temporary bug fix.',
        'Fix direct SV pagination not working correctly.',
        'Fixed flicker percentage not accurately converting to map.',
        'Fixed align timing lines not being deterministic.',
        'Fixed suffix of computableInputFloat.',
        'Fixed inconsistency of negative/positive SV generation.',
        'Fixed getRemovableSVs to use tolerance.',
        'Fixed the builder not properly nesting files.',
        'Fixed stills placing duplicate SVs.',
        'Fixed internal documentation being incorrect and generally poor.',
        'Fixed several overlapping SV issues.',
        'Fixed hypothetical SVs using some weird BS.',
        'Removed splitscroll in favor of using TGs.',
        'Fixed TG selector being unable to properly select some TGs.',
        'Fixed TG selector not always being fully in-sync with the game.',
        'Fixed automate altering SV post-effect.',
        'Fixed 2-side vibrato inaccuracy.',
        'Fixed build script to use correct regex.',
        'Fixed cursor trail being broken.',
        'Fixed hotkey settings window having overlapping text.',
        'Fixed global vars being unable to default to true.',
        'Moved workspace settings to .luarc file.',
        'Cached variables are properly reloaded during hot-reload.',
        'Fixed bug where hot-reloading would crash the game.',
        'Fixed starting fresh plugin with no config.yaml breaking style.',
        'Fixed bug where string ending of pluralized content\ncarried over between function calls.',
        'Fixed vibrato placing duplicate SVs.',
        'Fixed still per note group finally.',
        'Now properly instantiates pulse color.',
        'Fixed relative ratio not saving.',
        'Fixed Still per note group displacements, and enabled auto/otua on the \naforementioned feature.',
        'Fixed Select Bookmark crashing the game.',
        'Fixed Select Bookmark text going off the screen.',
        'Fixed measure msx widget not rendering in real time, and not\nproperly recalculating distances when switching TGs.',
        "Fixed bug where saving a false setting wouldn't save it at all.",
        "Fixed bug with certain functions where LN ends would not be\nconsidered if their start wasn't within the selection.",
    }

    local newFeatures = {
        'Added tooltips to various functions to explain their functionality.',
        'New border pulse feature that pulses along with the beat.',
        'Added a new hotkey to select the TG of note(s).',
        'New menu: Edit > Convert SV <-> SSF; Self-explanatory.',
        'Added vibrato to plumoguSV, with less error than AFFINE. Includes linear,\npolynomial, exponential, sinusoidal, and sigmoidal shapes. Includes presets for FPS.',
        'Include code-based SV/SSF fast place.',
        'New settings menu with many more customizable features.',
        'Allow defaults to be edited.',
        'Include some new automate parameters for further customization.',
        'Edit > Layer Snaps feature: Save your snap colors before using AFFINE to\nbring them back easily.',
        'Edit > Split feature: Split notes into different TGs with the\nsurrounding SVs in one click.',
        'Added linear equalizer to allow you to create 0x SV on linear much easier.',
        'Added custom theme input, along with exporting/importing.',
        'Added 3 custom reactive backgrounds. More will be added\nwhen the kofi products are paid for.',
        'Added copy paste slots; now you can copy paste more than one thing at once.',
        'Allow border pulse to be custom.',
        "Note lock feature: you don't need to worry about accidentally placing,\nmoving, or deleting notes during SV generation.",
        'Now allows certain inputs to be computed automatically on the backend.',
        'A new performance mode to speed up the FPS by 2-3x.',
        'You can now merge SSFs to eliminate duped ones.',
        'Added new option to allow combo-select.',
        'New toggleable SV Info visualizer for the more inexperienced mappers.',
        'Reworked bezier menu to be much more intuitive.',
        'Added loadup animation because why not.',
        'Added patch notes page.',
        'Added map stats button to quickly grab SV and SSF count.',
        'Added pagination to bookmarks.',
        'Now allowed Direct SV to view SVs around a particular note.',
        'Moved many linting features to Edit > Lint Map.',
        'Added new feature to remove duplicated notes.',
        "Added new feature to remove hitsounds, for mappers who don't use\nthem but accidentally click on the menu.",
        'Added a very rudimentary preset system, so you can send menu data to others.',
        'Added a button to directly swap SVs and SSFs.',
        'Added a startup animation.',
        'Added hotkeys to switch between TGs.',
        'Added hotkey to move all selected notes to the selected TG.',
    }

    local hueDegreeAdjust = (state.UnixTime % 7200) / 20 + 67
    local colFn = |x| color.vrgbaToUint(color.hslaToRgba(x + hueDegreeAdjust, 1, 0.7, 1))

    showPatchNotesElement('v2.0.0', 144, {rect = {lc,rc}, colFn = colFn}, {bugFixes = bugFixes, newFeatures = newFeatures})
end